spring:
  application:
    name: survey-web

#DataSource
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: 
    password:
    driver: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

security:
  user: 
    name: survey
    password: mudar@123